# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end

def oc_pod
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'Masonry', '1.1.0'
end

def swift_pod
  pod 'SnapKit', '5.6.0'
  pod 'SwiftyJSON', '5.0.1'
  pod 'Alamofire', '5.8.1'
end

target 'iosDev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosDev
  oc_pod
  swift_pod

end
